#!/bin/bash
# insta485db

# Stop on errors
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail

# Sanity check command line options
usage() {
  echo "Usage: $0 (create|destroy|reset|dump)"
}

create() {
  FILE="var/users.sqlite3"
  if [ -f "$FILE" ]; then
      echo "Error: database already exists"
      exit 1
  fi
  sqlite3 var/users.sqlite3 < sql/schema.sql
  sqlite3 var/users.sqlite3 < sql/data.sql
}

destroy() {
  rm -rf var/users.sqlite3
}

if [ $# -ne 1 ]; then
  usage
  exit 1
fi

# Parse argument.  $1 is the first argument
case $1 in
  "create")
    create
    ;;

  "destroy")
    destroy
    ;;

  "reset")
    destroy
    create
    ;;

  "dump")
    sqlite3 -batch -line var/users.sqlite3 'SELECT * FROM users'
    sqlite3 -batch -line var/users.sqlite3 'SELECT * FROM userItems'
    sqlite3 -batch -line var/users.sqlite3 'SELECT * FROM items'
    ;;
  *)
    usage
    exit 1
    ;;
esac